spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/in2l_local?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
#    username: in2l_local
#    password: yP1#^Y#6f3r6B1g
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      format_sql: true
#      ddl-auto: create

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

server:
  port: 5000

logging-module:
  version: 0.0.1

#  jpa:
#    open-in-view: true
#    hibernate:
#      ddl-auto: create
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      use-new-id-generator-mappings: false
#    show-sql: true
#    properties:
#      hibernate.format_sql: true
#      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#    defer-datasource-initialization: true

#apiVersion: "/api/v0"
#server:
#  port: 8081
#  tomcat:
#    remoteip:
#      protocol-header: x-forwarded-proto
#  shutdown: graceful
#
#logging:
#  level:
#    com:
#      zaxxer:
#        hikari: INFO
#    org:
#      springframework:
#        web: INFO
#        jdbc:
#          core:
#            JdbcTemplate: DEBUG
#            StatementCreatorUtils: TRACE
#      hibernate:
#        SQL: DEBUG
#      type:
#        descriptor:
#          sql:
#            BasicBinder: TRACE
#
#spring:
#  servlet:
#    multipart:
#      enabled: true
#      max-file-size: 100MB
#      max-request-size: 100MB
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/in2l_local?serverTimezone=Asia/Seoul
#    username: in2l_local
#    password: yP1#^Y#6f3r6B1g
#  #    data: data.sql
#  sql:
#    init:
#      mode: always
#
## Expose Http Trace
#management:
#  endpoints:
#    web:
#      exposure:
#        include: httptrace,health,flyway,env